import {
  ActivityItem,
  AdminTask,
  ChartPoint,
  Company,
  DashboardStats,
  JobAd,
  NotificationItem,
} from "@/types/admin";

export const dashboardStats: DashboardStats = {
  totalJobAds: 482,
  activeJobAds: 273,
  draftJobAds: 64,
  pendingApproval: 31,
  expiredAds: 42,
  rejectedAds: 19,
  archivedAds: 53,
  totalRecruiters: 116,
  totalApplicants: 4297,
};

export const jobs: JobAd[] = [
  {
    id: "JOB-1048",
    title: "Senior Product Designer",
    companyName: "Northstar Labs",
    companyId: "CMP-201",
    category: "Design",
    employmentType: "full_time",
    location: "Remote - US",
    salaryRange: "$120k-$150k",
    postedDate: "2026-04-08",
    expiryDate: "2026-05-08",
    status: "under_review",
    priority: "high",
    assignedReviewer: "Ava Wilson",
    featured: true,
    applicants: 54,
    description: "Lead design systems and product discovery for our hiring platform.",
    requirements: ["Figma", "Design systems", "User research"],
    benefits: ["Health insurance", "401k match", "Remote stipend"],
    notes: ["Portfolio quality is strong", "Needs compensation policy check"],
  },
  {
    id: "JOB-1049",
    title: "Backend Engineer (Node.js)",
    companyName: "Kepler Systems",
    companyId: "CMP-109",
    category: "Engineering",
    employmentType: "full_time",
    location: "Berlin, DE",
    salaryRange: "EUR70k-EUR90k",
    postedDate: "2026-04-10",
    expiryDate: "2026-05-01",
    status: "submitted",
    priority: "urgent",
    assignedReviewer: "Leo Carter",
    featured: false,
    applicants: 73,
    description: "Build APIs for ad ranking and moderation tooling.",
    requirements: ["Node.js", "PostgreSQL", "Redis"],
    benefits: ["Hybrid work", "Education budget"],
    notes: ["Company requests fast-track review"],
  },
  {
    id: "JOB-1050",
    title: "Technical Recruiter",
    companyName: "Orbit People",
    companyId: "CMP-178",
    category: "HR",
    employmentType: "part_time",
    location: "London, UK",
    salaryRange: "GBP45k-GBP60k",
    postedDate: "2026-03-29",
    expiryDate: "2026-04-29",
    status: "approved",
    priority: "medium",
    assignedReviewer: "Nina Brooks",
    featured: false,
    applicants: 21,
    description: "Own full-cycle hiring for product and engineering roles.",
    requirements: ["Sourcing", "Interview design"],
    benefits: ["Bonus", "Private healthcare"],
    notes: ["Approved with minor copy edits"],
  },
  {
    id: "JOB-1051",
    title: "Data Analyst",
    companyName: "Verve Health",
    companyId: "CMP-042",
    category: "Data",
    employmentType: "contract",
    location: "Toronto, CA",
    salaryRange: "$65/hr-$85/hr",
    postedDate: "2026-03-18",
    expiryDate: "2026-04-18",
    status: "expired",
    priority: "low",
    assignedReviewer: "Ava Wilson",
    featured: false,
    applicants: 12,
    description: "Analyze hiring funnel conversion and campaign quality.",
    requirements: ["SQL", "BI tools"],
    benefits: ["Flexible schedule"],
    notes: ["Renewal requested by company"],
  },
  {
    id: "JOB-1052",
    title: "iOS Engineer",
    companyName: "Pixel Freight",
    companyId: "CMP-066",
    category: "Engineering",
    employmentType: "full_time",
    location: "Austin, TX",
    salaryRange: "$130k-$165k",
    postedDate: "2026-04-11",
    expiryDate: "2026-05-20",
    status: "rejected",
    priority: "high",
    assignedReviewer: "Leo Carter",
    featured: false,
    applicants: 8,
    description: "Build recruiter-facing iOS features and admin control panels.",
    requirements: ["Swift", "UIKit", "Testing"],
    benefits: ["Stock options", "401k"],
    notes: ["Rejected for policy violation in compensation language"],
  },
  {
    id: "JOB-1053",
    title: "Growth Marketing Manager",
    companyName: "Northstar Labs",
    companyId: "CMP-201",
    category: "Marketing",
    employmentType: "full_time",
    location: "Remote - EU",
    salaryRange: "EUR62k-EUR80k",
    postedDate: "2026-04-01",
    expiryDate: "2026-05-15",
    status: "published",
    priority: "medium",
    assignedReviewer: "Nina Brooks",
    featured: true,
    applicants: 41,
    description: "Run paid and organic growth campaigns for enterprise hiring.",
    requirements: ["B2B marketing", "Lifecycle"],
    benefits: ["Remote allowance", "Training credits"],
    notes: ["Strong performance in first week"],
  },
  {
    id: "JOB-1054",
    title: "QA Automation Engineer",
    companyName: "Kepler Systems",
    companyId: "CMP-109",
    category: "Engineering",
    employmentType: "full_time",
    location: "Warsaw, PL",
    salaryRange: "PLN18k-PLN24k",
    postedDate: "2026-04-05",
    expiryDate: "2026-06-01",
    status: "draft",
    priority: "medium",
    assignedReviewer: "Ava Wilson",
    featured: false,
    applicants: 0,
    description: "Own automated testing strategy across backend services.",
    requirements: ["Playwright", "CI/CD"],
    benefits: ["Private healthcare", "Hybrid setup"],
    notes: ["Draft awaiting recruiter edits"],
  },
  {
    id: "JOB-1055",
    title: "Customer Success Lead",
    companyName: "Atlas Loop",
    companyId: "CMP-078",
    category: "Customer Success",
    employmentType: "full_time",
    location: "New York, NY",
    salaryRange: "$95k-$120k",
    postedDate: "2026-02-12",
    expiryDate: "2026-04-12",
    status: "archived",
    priority: "low",
    assignedReviewer: "Nina Brooks",
    featured: false,
    applicants: 38,
    description: "Drive enterprise onboarding and retention outcomes.",
    requirements: ["SaaS CS", "Leadership"],
    benefits: ["Health", "Commuter benefits"],
    notes: ["Role closed and archived"],
  },
];

export const activities: ActivityItem[] = [
  {
    id: "ACT-1",
    label: "Job moved to under review",
    actor: "Ava Wilson",
    timestamp: "5m ago",
    type: "review",
  },
  {
    id: "ACT-2",
    label: "Company verification approved",
    actor: "Nina Brooks",
    timestamp: "17m ago",
    type: "company",
  },
  {
    id: "ACT-3",
    label: "Urgent moderation task assigned",
    actor: "System",
    timestamp: "34m ago",
    type: "task",
  },
  {
    id: "ACT-4",
    label: "New job ad submitted",
    actor: "Northstar Labs",
    timestamp: "1h ago",
    type: "job",
  },
];

export const companies: Company[] = [
  {
    id: "CMP-201",
    name: "Northstar Labs",
    verified: true,
    status: "active",
    totalAds: 43,
    activeListings: 17,
    approvalRate: 92,
    rejectionRate: 8,
    lastActivity: "2026-04-12",
    primaryRecruiter: "Jamie Ortega",
  },
  {
    id: "CMP-109",
    name: "Kepler Systems",
    verified: true,
    status: "active",
    totalAds: 37,
    activeListings: 14,
    approvalRate: 84,
    rejectionRate: 16,
    lastActivity: "2026-04-11",
    primaryRecruiter: "Sofia Reed",
  },
  {
    id: "CMP-078",
    name: "Atlas Loop",
    verified: false,
    status: "suspended",
    totalAds: 16,
    activeListings: 1,
    approvalRate: 55,
    rejectionRate: 45,
    lastActivity: "2026-03-18",
    primaryRecruiter: "Liam Wood",
  },
];

export const tasks: AdminTask[] = [
  {
    id: "TASK-301",
    title: "Review compensation policy compliance",
    linkedJobId: "JOB-1052",
    assignedAdmin: "Leo Carter",
    priority: "urgent",
    dueDate: "2026-04-24",
    status: "in_progress",
    comments: 4,
  },
  {
    id: "TASK-302",
    title: "Audit duplicate listings for CMP-109",
    linkedJobId: "JOB-1049",
    assignedAdmin: "Ava Wilson",
    priority: "high",
    dueDate: "2026-04-25",
    status: "todo",
    comments: 1,
  },
  {
    id: "TASK-303",
    title: "Finalize moderation workflow update",
    linkedJobId: "JOB-1050",
    assignedAdmin: "Nina Brooks",
    priority: "medium",
    dueDate: "2026-04-27",
    status: "blocked",
    comments: 7,
  },
];

export const jobsByWeek: ChartPoint[] = [
  { label: "W1", value: 42 },
  { label: "W2", value: 58 },
  { label: "W3", value: 65 },
  { label: "W4", value: 49 },
  { label: "W5", value: 71 },
];

export const statusDistribution: ChartPoint[] = [
  { label: "Draft", value: 64 },
  { label: "Submitted", value: 31 },
  { label: "Under Review", value: 46 },
  { label: "Published", value: 273 },
  { label: "Rejected", value: 19 },
  { label: "Archived", value: 53 },
];

export const approvalTrend: ChartPoint[] = [
  { label: "Jan", approved: 74, rejected: 12, value: 0 },
  { label: "Feb", approved: 88, rejected: 18, value: 0 },
  { label: "Mar", approved: 95, rejected: 16, value: 0 },
  { label: "Apr", approved: 101, rejected: 14, value: 0 },
];

export const categories: ChartPoint[] = [
  { label: "Engineering", value: 142 },
  { label: "Design", value: 69 },
  { label: "Marketing", value: 58 },
  { label: "Data", value: 41 },
  { label: "HR", value: 33 },
];

export const notifications: NotificationItem[] = [
  {
    id: "NOT-1",
    title: "New job ad submitted by Kepler Systems",
    time: "2m",
    type: "submission",
    unread: true,
  },
  {
    id: "NOT-2",
    title: "Approval pending for JOB-1048",
    time: "18m",
    type: "approval",
    unread: true,
  },
  {
    id: "NOT-3",
    title: "Northstar Labs requested verification update",
    time: "1h",
    type: "company",
    unread: false,
  },
  {
    id: "NOT-4",
    title: "TASK-302 assigned to Ava Wilson",
    time: "3h",
    type: "task",
    unread: false,
  },
];
